# .readthedocs.yaml
# Read the Docs configuration file (https://docs.readthedocs.io/en/stable/config-file/v2.html)

version: 2

build:
   os: ubuntu-22.04
   tools:
     python: "3.11"
   apt_packages:
     - gcc-10
     - g++-10
   jobs:
     pre_create_environment:
       - echo "Getting test data"
       - cd docs && wget -q http://star.ucl.ac.uk/~app/testdata.tar.gz && tar --exclude="._*" -xzvf testdata.tar.gz
       - cd docs && wget https://zenodo.org/records/10825178/files/tutorial_gadget4.tar.gz?download=1 -O tutorial_gadget4.tar.gz && tar -xvzf tutorial_gadget4.tar.gz

sphinx:
   configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - all